char **parseLine(char *line, int *and);
int isValid(char **args);
void runningAgain(int pid);
void suspend(int sig);
void terminate(int sig);
void printChildren();
void addChild(int id, char **input, int bg);
int getPid(int jid);
int sighupIt();
int sigcontIt();
int findCommand(int pid);
int updateBackground(int jid);
void freeThemAll();
void emptyOut(int newStart);
int unaliveChild(int pid);
void childKilled(int pid, int sig);
void childStopped(int pid);
void childContinues(int pid, int bg);
void checkOnKids();
void background(char **argv);
int lookup(char** cmd);
